version: '3.3'

services:
  redis:
    container_name: redis
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'     

  postgres:
    container_name: postgres
    image: 'postgres:15'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tracker2  

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres/tracker2?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  

