-- drop table demo;
DROP TABLE IF EXISTS metric;
DROP TABLE IF EXISTS conversion;
DROP TABLE IF EXISTS traffic_source_token;
DROP TABLE IF EXISTS lander;
DROP TABLE IF EXISTS offer;
DROP TABLE IF EXISTS hit_query_string;
DROP TABLE IF EXISTS hit;
DROP TABLE IF EXISTS affiliate_network;
DROP TABLE IF EXISTS campaign;
DROP TABLE IF EXISTS traffic_source;
DROP TABLE IF EXISTS flow;
